decode: fix build on ARMv7 targets
Building NEON code on ARMv7 fails with the following error:

...../src/NextStartCodeNEON.cpp:39:57: error: cannot convert 'uint8x8_t' to 'uint64x1_t'

Add missing vreinterpret call in order to fix that error.

Fixes KhronosGroup/VK-GL-CTS#547

Signed-off-by: Dmitry Baryshkov <dmitry.baryshkov@oss.qualcomm.com>